# Check on http://lint.travis-ci.org/ after modifying it!
sudo: false
language: c
os:
  - linux
env:
  - PYVERSION="2.7"
before_install:
  - echo "$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - hash -r
  # Update conda itself
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - conda create -n test_env python=$PYVERSION --file ci/conda_requirements.txt
  - source activate test_env
  - pip install -r ci/pip_requirements.txt
  - pip install . --no-deps
script:
  - WITH_COVERAGE=TRUE make all
after_success:
  - coveralls
notifications:
  webhooks:
    on_success: change
    on_failure: always
